UTILITIES = [
    "find",
    "xargs",
    "grep",
    "rm",
    "echo",
    "ls",
    "sort",
    "chmod",
    "wc",
    "cat",
    "cut",
    "head",
    "mv",
    "chown",
    "cp",
    "mkdir",
    "tr",
    "tail",
    "dirname",
    "tar",
    "uniq",
    "ln",
    "split",
    "tee",
    "date",
    "pwd",
    "ssh",
    "diff",
    "du",
    "file",
    "rename",
    "md5sum",
    "comm",
    "mktemp",
    "df",
    "rev",
    "rmdir",
    "od",
    "hostname",
]

ARG_TYPES = [
    'Regex',
    'File',
    'Directory',
    'Path',
    'Number',
    'Quantity',
    'Size',
    '+Size',
    '-Size',
    'Timespan',
    'DateTime',
    'Permission',
]

TYPE_MAPS = {
    'Regex': {'str', 'sep', 'pattern', 'word', 'delim', 'suffix', 'from', 'glob'},
    'File': {'file'},
    'Directory': {'dir'},
    'Path': {'path'},
    'Number': {'num', 'n', 'cols', 'pid', 'max', 'bytes'},
    'Quantity': {},
    'Size':{'size'},
    'Timespan':{},
    'DateTime': {'timestamp', 'time'},
    'Permission':{},
}